[platformio]
default_envs = pixelexpression
boards_dir = boards
src_dir = PixelExpression

[env]
platform = espressif32@6.10.0
framework = arduino
board = esp32s3box
upload_speed = 921600
upload_port = /dev/cu.usbmodem14401
monitor_port = /dev/cu.usbmodem14401
monitor_speed = 115200
board_build.partitions = partitions_app3M_fat9M_16MB.csv
board_build.filesystem = fatfs
board_build.flashmode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
build_unflags =
  -Os
  -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
  -Os
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_MSC_ON_BOOT=0
  -DARDUINO_USB_DFU_ON_BOOT=0
  -DBOARD_HAS_PSRAM
  -DIS_SPIRAM
  -mfix-esp32-psram-cache-issue
lib_extra_dirs =
  /Users/huangzhilong/Library/Arduino15/libraries
  /Users/huangzhilong/Documents/Arduino/libraries
lib_deps =

[env:pixelexpression]
extends = env
board_build.arduino.memory_type = qio_opi
